### ISSUE TITLE
[Feature]: Implémentation d'images Docker (OxygenCS)

### ISSUE THREAD

**Issue by turbowarrior** [log680-equipe07/etsmtl-log680-oxygencs#7]
### Informations sur le feature

Ajouté une image Docker pour l'application OxygenCS

Se renseigner sur Docker au besoin.

**Comment by turbowarrior** [comment]
L'image est créée.

Une autre tâche doît être créer afin d'optimiser l'image Docker créée.

**Comment by TurboWarrior** [comment]
Tâche bloquée jusqu'à temps que l'image soit optimisée
